### PR TITLE
reply_to is filled if the user is authenticated

### PR DESCRIPTION
**Pull request by dethos**
Addresses #218 

This is a simple implementation of a requested feature. If a user is logged in when submitting a box, the `reply_to` field will be filled with his email address. 

We could added a field for users not logged in, however we would have to validate the users is not trying to impersonate (not providing is own email address). 

A possible improvement for this PR, would be to allow the logged in user to opt out of this feature.
Would that be preferable?

### CODE REVIEW

**Comment by dethos** [comment]
any news about this?

**Review by pjaneiro — COMMENTED** [review]
@dethos just to clarify. If I'm filling a box, and am logged in, my e-mail will be used in the `reply_to` field? Is that the expected behaviour?

**Comment by dethos** [comment]
Yes, so the receiver can know who sent it (or to whom he should reply). 
Thinking a little more about this:

> A possible improvement for this PR, would be to allow the logged in user to opt out of this feature.
> Would that be preferable?

I think Hawkpost should give the user the possibility to add this information. So instead of being `opt-out` we should aim for it to be `opt-in` :thinking:

**Comment by pjaneiro** [comment]
Yes, considering the specific task, I think `opt-in` would be preferable here. Should that be addressed in this PR, or should a new PR be created just with that purpose?

**Comment by dethos** [comment]
@pjaneiro just made it `opt-in`. Authenticated users now can check a `checkbox` in case they want their email added to `ReplyTo`.

**Comment by dethos** [comment]
@pjaneiro any news?

**Review by pjaneiro — APPROVED** [review]
LGTM. Merge away :+1:

**Pull request merged**
