### PR TITLE
Add option to restrict box to autenticated users

### PR DESCRIPTION
**Pull request by pdcribeiro**
Takes care of #180. It's still missing the OTP option, though

### CODE REVIEW

**Review by dethos — APPROVED** [review]
Looks good to me :+1: . 

Before merging I would like to discuss the integration with other existing feature. At the moment if the "sender" is logged in and gives permission we include the user's email address in the `Reply-To` field. The code is the following:

```python
            add_user_email = cleaned_data.get("add_reply_to", False)
            if request.user.is_authenticated and add_user_email:
                user_email = request.user.email
            else:
                user_email = None
            # Schedule e-mail
            process_email.delay(
                message.id, form.cleaned_data, sent_by=user_email
            )
```
Should we change things to always include this "field" for boxes marked as `verified_only`? It would also require changing the template (and js) replacing the checkbox with a message informing the user that his email will be shared with the box owner.

I think this change makes sense, otherwise the receiver will still not know who submitted.

**Comment by pdcribeiro** [comment]
Sorry, I forgot about that part :b Sounds good to me. I'll try to find some time to take care of that

**Comment by dethos** [comment]
@pdcribeiro any news/progress on this front?

**Comment by dethos** [comment]
It doesn't seem that there will be much more activity in this PR. The feature looks good and the suggested improvements can be added later.

**Pull request merged**
