### PR TITLE
Improve spacing

### PR DESCRIPTION
**Pull request by macbookandrew**
improve spacing and make wording a bit more recipient-focused instead of sender-focused, since primarily recipients will see this submission page

### CODE REVIEW

**Comment by jlbribeiro** [comment]
@macbookandrew Hi, thanks for your contribution!

Your code update is actually in conflict with master right now.

Not only that but this throws a syntax error: [box_submit.js#L66](https://github.com/whitesmith/hawkpost/pull/188/files#diff-7ab11b5e838ce1918cee2746e5f9092bR66). I believe you're using PHP's concatenation operator?

There's currently an older pending PR (#173) that considerable refactors that structure; ping me after fixing your PR, so I may rebase #173 (otherwise it will get merged first).

**Comment by jlbribeiro** [comment]
(sorry, pressed the close-and-comment button by mistake)

**Comment by macbookandrew** [comment]
@jlbribeiro Thanks—updated. You’re right, I did use PHP concatenation instead of JS 😳

**Comment by jlbribeiro** [comment]
Hello @macbookandrew!

I believe [this](https://github.com/whitesmith/hawkpost/pull/188/commits/1bdca0205190c91a6068e0d94308c907b8bce897#diff-7ab11b5e838ce1918cee2746e5f9092bR66) does not work as expected, since you're concatenating strings with a selector. Have you been able to test this on your end?

object Object

If you want I may pick up your changes and amend them (that would require a different PR, though; you would appear as a co-author of the commits).

Thank you once again for your contribution!

(PS: and sorry for taking so long to review)

**Comment by macbookandrew** [comment]
@jlbribeiro Sorry, I haven’t gotten the dev environment running on my local machine to test it out locally.

However, I just noticed a couple lines above that the `.append()` function is being used to do a similar thing, so I just updated my code to use that.

If that’s still causing trouble, then by all means pick up and amend my changes. Would you need a different PR from me, or would that be from you?

Thanks!

**Comment by dethos** [comment]
@jlbribeiro @macbookandrew 
Thank for your contribution. However this PR is out of date and since it has been inactive for the last 10 months I will close it.

If you still desire to complete these changes add a comment to this issue and I will reopen it.

**Pull request closed without merging**
