### PR TITLE
Remove pyup and fix typo in a docstring

### PR DESCRIPTION
**Pull request by dethos**
Removes a service that no longer is being used and an alternative is already provided by GitHub.

closes #316

### CODE REVIEW

**Review by lopesrb — APPROVED** [review]
Looks good. Should we also add the config file for dependabot?

**Comment by dethos** [comment]
> Looks good. Should we also add the config file for dependabot?

@lopesrb Any suggestion for configs not included by default?

**Comment by lopesrb** [comment]
@dethos I don't know the defaults but probably update_schedule and default_reviewers
feel free to ignore if you find that's not necessary

**Comment by dethos** [comment]
@lopesrb It took a while :), but here it is. Can you review again?

**Review by lopesrb — APPROVED** [review]

**Comment by lopesrb** [comment]
@dethos looks good :)

**Comment by dethos** [comment]
Thanks. Well it seems I still can't merge, this repository settings must be messed up. Ping @pjaneiro .

**Review by pjaneiro — APPROVED** [review]

**Pull request merged**
