### PR TITLE
Handle box not found

### PR DESCRIPTION
**Pull request by pdcribeiro**

### CODE REVIEW

**Comment by pdcribeiro** [comment]
Should I add [these](https://github.com/whitesmith/hawkpost/pull/307/commits/a4a5b0b15ec0234c50754587f94656b2e4555d47) changes as well?

**Comment by pdcribeiro** [comment]
@dethos, I'm deleting the other PR. Should I add [these](https://github.com/whitesmith/hawkpost/pull/307/commits/a4a5b0b15ec0234c50754587f94656b2e4555d47) changes here as well?

**Review by dethos — APPROVED** [review]
Looks good to me

**Comment by dethos** [comment]
> @dethos, I'm deleting the other PR. Should I add [these](https://github.com/whitesmith/hawkpost/pull/307/commits/a4a5b0b15ec0234c50754587f94656b2e4555d47) changes here as well?

If they aren't related to this feature, they should have their own PR.

**Pull request merged**
