### PR TITLE
Email users

### PR DESCRIPTION
**Pull request by dethos**
When the administrator of one Hawkpost instance wants to communicate to its users an issue or important information, such as downtime for maintenance, it now can use this simple built in feature.

### CODE REVIEW

**Comment by jlbribeiro** [comment]
@dethos: Most functionality seems ok, but deleting an already sent notification gives me this:

Failed and succeeded

**Comment by dethos** [comment]
@jlbribeiro: To delete the success message we would have to override [this huge function](https://github.com/django/django/blob/master/django/contrib/admin/options.py#L1319), that is why I opted to leave it there (since it is only visible to admins):

**Comment by jlbribeiro** [comment]
@dethos 
I'm not sure of the sequence of actions I performed over a notification, but some of them are blank:

Empty actions

It seems good to go. Do you want to fix this first or may I merge it?

**Comment by jlbribeiro** [comment]
Not worth holding the PR. Merging.

**Pull request merged**
